#!/usr/bin/with-contenv bash

HOME=/mnt/config/home

if [[ ! -d /mnt/config/data ]]; then
  s6-setuidgid guardian mkdir /mnt/config/data
fi

if [[ -L /srv/unifi/data ]]; then
  unlink /srv/unifi/data
fi
s6-setuidgid guardian ln -s /mnt/config/data /srv/unifi/data

if [[ -L /srv/unifi/logs ]]; then
  unlink /srv/unifi/logs
fi
s6-setuidgid guardian ln -s /mnt/config/log /srv/unifi/logs